services:
  php:
    container_name: api_backend
    build: 
      context: ./docker/php
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    volumes:
      - ./laravel:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel-network
  nginx:
    container_name: nginx
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    ports:
      - '8080:80'
      - '443:443'
    volumes:
      - ./laravel:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel-network

  mysql:
    container_name: mysql
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    tty: true
    volumes:
      - data:/var/lib/mysql/
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - laravel-network
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: boardnet
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:5.2
    restart: always
    ports:
      - '8888:80'
    networks:
      - laravel-network
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      PMA_HOST: mysql
    depends_on:
      - mysql
  redis:
    container_name: redis
    restart: unless-stopped
    build:
      context: ./docker/redis
      dockerfile: Dockerfile
    ports:
      - '6379:6379'
  vite:
    container_name: vite
    restart: unless-stopped
    image: node:20
    working_dir: /var/www
    volumes:
      - ./laravel:/var/www
    command: sh -c "npm install && npm run dev"
    ports:
      - "5173:5173"

networks:
  laravel-network:
    driver: bridge

volumes:
  data:
    driver: local